### ISSUE TITLE
Lab2 Feedback

### ISSUE THREAD

**Issue by alanarnholt** [STT3851-Fall2019/lab2-Ryanwhitt1#1]
@Ryanwhitt1 

1) Equation 2.1 uses html tags versus Rmarkdown syntax...it also has pasted equations versus valid LaTeX...this will not work if the document type is changed to pdf.

2) The reference to equation (3.1) needs to be hyperlinked and right before that the k needs to a subscript in f_k(X=x).

The rest looks great.

**Comment by Ryanwhitt1** [comment]
@alanarnholt Changes made.
